apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
    tier: db
    release: demo
    version: "5.7"
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: root