apiVersion: v1
kind: Pod
metadata:
  name: myweb
  labels:
    app.kubernetes.io/name: myweb
    app.kubernetes.io/managed-by: manual
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
    - name: nginx
      image: nginx:1.19
      ports:
        - name: http
          containerPort: 80
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
  initContainers:
      - name: init
        image: alpine
        command: ["/bin/sh", "-c"]
        args:
          - >
            echo "Te amo mi princesa!" > /html/index.html
        volumeMounts:
          - name: html
            mountPath: /html